services:
  brewica-postgres:
    env_file:
      - ../.env
    image: postgres:16-alpine
    container_name: brewica-postgres
    restart: unless-stopped
    volumes:
      - brewica_postgres_data:/var/lib/postgresql/data
    networks:
      - brewica-internal

networks:
  brewica-internal:
    name: brewica_internal
    external: false

volumes:
  brewica_postgres_data:
