import * as mongoose from 'mongoose';

export interface IUser {
    _id?: string;
    username: string;
    emailAddress: string;
    password: string;
    passwordConf: string;
    token?: string;
    verified?: boolean;
    expiresAt?: Date;
};

export interface ISignIn {
    emailAddress: string;
    password: string;
}

export type Props = {
    password: string
}

export interface ICoffee {
    name: string,
    country: string,
    region?: string,
    producer?: string,
    varieties?: string[],
    process?: string,
    elevationMin?: number,
    elevationMax?: number,
    decaf: boolean
}

export interface IRoaster {
    user: mongoose.Types.ObjectId,
    name: string,
    coffee: ICoffee[]
}

export enum coffeeCountries {
    Angola = "Angola",
    Belize = "Belize",
    Benin = "Benin",
    Bolivia = "Bolivia (Plurinational State of)",
    Brazil = "Brazil",
    Burundi = "Burundi",
    CaboVerde = "Cabo Verde",
    Cambodia = "Cambodia",
    Cameroon = "Cameroon",
    CentralAfricanRepublic = "Central African Republic",
    China = "China",
    Taiwan = "Taiwan",
    Colombia = "Colombia",
    Comoros = "Comoros",
    Congo = "Congo",
    CookIslands = "Cook Islands",
    CostaRica = "Costa Rica",
    CotedIvoire = "Côte d'Ivoire",
    Cuba = "Cuba",
    DRCongo = "Democratic Republic of the Congo",
    Dominica = "Dominica",
    DominicanRepublic = "Dominican Republic",
    Ecuador = "Ecuador",
    ElSalvador = "El Salvador",
    EquatorialGuinea = "Equatorial Guinea",
    Ethiopia = "Ethiopia",
    Fiji = "Fiji",
    FrenchPolynesia = "French Polynesia",
    Gabon = "Gabon",
    Ghana = "Ghana",
    Guadeloupe = "Guadeloupe",
    Guatemala = "Guatemala",
    Guinea = "Guinea",
    Guyana = "Guyana",
    Haiti = "Haiti",
    Hawaii = "Hawaii",
    Honduras = "Honduras",
    India = "India",
    Indonesia = "Indonesia",
    Jamaica = "Jamaica",
    Kenya = "Kenya",
    LaoPDR = "Lao People's Democratic Republic",
    Liberia = "Liberia",
    Madagascar = "Madagascar",
    Malawi = "Malawi",
    Malaysia = "Malaysia",
    Martinique = "Martinique",
    Mauritius = "Mauritius",
    Mexico = "Mexico",
    Mozambique = "Mozambique",
    Myanmar = "Myanmar",
    Nepal = "Nepal",
    NewCaledonia = "New Caledonia",
    Nicaragua = "Nicaragua",
    Nigeria = "Nigeria",
    Panama = "Panama",
    PapuaNewGuinea = "Papua New Guinea",
    Paraguay = "Paraguay",
    Peru = "Peru",
    Philippines = "Philippines",
    PuertoRico = "Puerto Rico",
    Rwanda = "Rwanda",
    SaintLucia = "Saint Lucia",
    SaintVincentGrenadines = "Saint Vincent and the Grenadines",
    Samoa = "Samoa",
    SaoTomePrincipe = "Sao Tome and Principe",
    SaudiArabia = "Saudi Arabia",
    SierraLeone = "Sierra Leone",
    Spain = "Spain",
    SriLanka = "Sri Lanka",
    Suriname = "Suriname",
    Thailand = "Thailand",
    TimorLeste = "Timor-Leste",
    Togo = "Togo",
    Tonga = "Tonga",
    TrinidadTobago = "Trinidad and Tobago",
    Uganda = "Uganda",
    Tanzania = "United Republic of Tanzania",
    Vanuatu = "Vanuatu",
    Venezuela = "Venezuela (Bolivarian Republic of)",
    VietNam = "Viet Nam",
    Yemen = "Yemen",
    Zambia = "Zambia",
    Zimbabwe = "Zimbabwe",
}

export enum coffeeVarieties {
    Ababuna = "Ababuna",
    Agaro = "Agaro",
    Alghe = "Alghe",
    AmarellodeBotucatu = "Amarello de Botucatu",
    Anacafe14 = "Anacafe 14",
    Arabigo = "Arabigo",
    Arla = "Arla",
    Arusha = "Arusha",
    Ateng = "Ateng",
    Awada = "Awada",
    BarbukSudan = "Barbuk Sudan",
    Batian = "Batian",
    BergundalGarundang = "Bergundal AKA Garundang",
    BlawanPaumah = "Blawan Paumah",
    BlueMountain = "Blue Mountain",
    BMJ = "BMJ",
    BogorPrada = "Bogor Prada",
    Bourbon = "Bourbon",
    BourbonChocola = "Bourbon Chocolá",
    BourbonPointuLaurina = "Bourbon Pointu/Laurina",
    Castillo = "Castillo",
    CatigaMG2 = "Catiga MG2",
    Catigua = "Catigua",
    Catimore = "Catimore",
    Catrenic = "Catrenic",
    Catuai = "Catuai",
    Catucai = "Catucai",
    Caturra = "Caturra",
    Cera = "Cera",
    Chickumalgur = "Chickumalgur",
    CioccieS6 = "Cioccie S6",
    Colombia = "Colombia",
    CostaRica95 = "Costa Rica 95 AKA CR-95",
    Criollo = "Criollo",
    Dalle = "Dalle",
    Dega = "Dega",
    Devamachy = "Devamachy",
    Dilla = "Dilla",
    Djimma = "Djimma",
    Ennarea = "Ennarea",
    Frenchmission = "French mission",
    Gawe = "Gawe",
    Gera = "Gera",
    Gesha = "Gesha",
    Ghimbi = "Ghimbi",
    Guatemala = "Guatemala",
    Harrar = "Harrar",
    Haru = "Haru",
    IAPAR59 = "IAPAR 59",
    Ibairi = "Ibairi",
    ICAFE95 = "ICAFE 95",
    Icatu = "Icatu",
    IHCAFE90 = "IHCAFE 90",
    IPAR103 = "IPAR 103",
    Jackson = "Jackson",
    Jackson21257 = "Jackson 2/1257",
    Java = "Java",
    JemberS795 = "Jember/S795",
    K20 = "K20",
    K7 = "K7",
    Kalimas = "Kalimas",
    Kawisari = "Kawisari",
    Kent = "Kent",
    Kona = "Kona",
    Lekempti = "Lekempti",
    Lempira = "Lempira",
    LongberryHarrar = "Longberry Harrar",
    Maracatu = "Maracatu",
    Maracaturra = "Maracaturra",
    Maragogype = "Maragogype",
    Marsellesa = "Marsellesa",
    Mayaguez = "Mayaguez",
    Mechara = "Mechara",
    Melka = "Melka",
    MelkoCH2 = "Melko-CH2",
    Menado = "Menado",
    Mettu = "Mettu",
    Mibirizi = "Mibirizi",
    MochaMokka = "Mocha/Mokka",
    Mugi = "Mugi",
    MundoNovo = "Mundo Novo",
    Obata = "Obata",
    Orangebourbon = "Orange bourbon",
    OroAzteca = "Oro Azteca",
    OuroBronze = "Ouro Bronze",
    OuroVerde = "Ouro Verde",
    Pacamara = "Pacamara",
    Pacas = "Pacas",
    PacheColis = "Pache Colis",
    PacheComum = "Pache Comum",
    Parainema = "Parainema",
    Paraiso = "Paraiso",
    PinkBourbon = "Pink Bourbon",
    PlumaHidalgo = "Pluma Hidalgo",
    Rambung = "Rambung",
    Rasuna = "Rasuna",
    RedBourbon = "Red Bourbon",
    Rubi = "Rubi",
    Ruiru11 = "Ruiru 11",
    RumeSudan = "Rume Sudan",
    S26 = "S26",
    S288 = "S288",
    SanBernardoPache = "San Bernardo AKA Pache",
    SanRamon = "San Ramon",
    Sarchimor = "Sarchimor",
    Selection9 = "Selection 9",
    Semperflorens = "Semperflorens",
    Sidamo = "Sidamo",
    Sidikalang = "Sidikalang",
    SL28 = "SL28",
    SL34 = "SL34",
    Sumatra = "Sumatra",
    Tabi = "Tabi",
    Tafarikela = "Tafarikela",
    Tegu = "Tegu",
    Tekisic = "Tekisic",
    TimorHybrid = "Timor Hybrid",
    Tupi = "Tupi",
    Typica = "Typica",
    USDA762 = "USDA 762",
    VillaSarchi = "Villa Sarchi",
    Villalobos = "Villalobos",
    Wellega = "Wellega",
    Wenago = "Wenago",
    YellowBourbon = "Yellow Bourbon",
    Yirgacheffe = "Yirgacheffe",
}

export enum coffeeProcesses {
    Natural = "Natural",
    HoneyPulpedNAtural = "Honey / Pulped Natural",
    WhiteHoney = "White Honey",
    YellowHoney = "Yellow Honey",
    RedHoney = "Red Honey",
    BlackHoney = "Black Honey",
    Washed = "Washed",
    WetHulled = "Wet Hulled",
    GilingBasah = "Giling Basah",
    Koji = "Koji",
    Lactic = "Lactic",
    CarbonicMaceration = "Carbonic Maceration",
    CarbonicWashed = "Carbonic Washed",
    Anaerobic = "Anaerobic",
}