name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - run: npm ci

      - run: npx nx format:check --all

      - run: npm run db:generate

      - run: npx nx run-many -t lint test build typecheck

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and export web to Docker
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: apps/web/Dockerfile
          load: true
          tags: brewica-web:test

      - name: Test web image
        run: |
          docker run --rm -d -p 3000:3000 --name brewica-web-test brewica-web:test
          sleep 5
          curl --fail http://localhost:3000 || exit 1
          docker stop brewica-web-test

      - name: Build and export api to Docker
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: apps/api/Dockerfile
          load: true
          tags: brewica-api:test

      - name: Test api image
        run: |
          docker run --rm -d -p 4000:4000 --name brewica-api-test brewica-api:test
          sleep 5
          curl --fail http://localhost:4000/api || exit 1
          docker stop brewica-api-test

      - name: Log in to the Container registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@36864503dc2a3702db7dc554479e3e1a29bb8337
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for web
        if: github.ref == 'refs/heads/main'
        id: meta-web
        uses: docker/metadata-action@deaa0dee567db6b95038c14152b037af85a8fe3b
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/brewica-web

      - name: Build and push web image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}

      - name: Extract metadata for api
        if: github.ref == 'refs/heads/main'
        id: meta-api
        uses: docker/metadata-action@deaa0dee567db6b95038c14152b037af85a8fe3b
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/brewica-api

      - name: Build and push api image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: apps/api/Dockerfile
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}
